# Import the required libraries

In [108]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import TruncatedSVD
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

# Read the data from train.csv

In [ ]:
train = pd.read_csv('train.csv')

In [70]:
print("Train Data - Overview:")
train.head()

Train Data - Overview:

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

# Collect the Y values into an array

In [73]:
y_values = train['y'].values

# Understand the data types we have

In [74]:
print("\nTrain Data - Data Types:")
for col in train.columns:
    if 'X' in col:
        print(f"{col}: {train[col].dtype}")

Train Data - Data Types:
X0: object
X1: object
X2: object
X3: object
X4: object
X5: object
X6: object
X8: object
X10: int64
X11: int64
X12: int64
X13: int64
X14: int64
X15: int64
X16: int64
X17: int64
X18: int64
X19: int64
X20: int64
X21: int64
X22: int64
X23: int64
X24: int64
X26: int64
X27: int64
X28: int64
X29: int64
X30: int64
X31: int64
X32: int64
X33: int64
X34: int64
X35: int64
X36: int64
X37: int64
X38: int64
X39: int64
X40: int64
X41: int64
X42: int64
X43: int64
X44: int64
X45: int64
X46: int64
X47: int64
X48: int64
X49: int64
X50: int64
X51: int64
X52: int64
X53: int64
X54: int64
X55: int64
X56: int64
X57: int64
X58: int64
X59: int64
X60: int64
X61: int64
X62: int64
X63: int64
X64: int64
X65: int64
X66: int64
X67: int64
X68: int64
X69: int64
X70: int64
X71: int64
X73: int64
X74: int64
X75: int64
X76: int64
X77: int64
X78: int64
X79: int64
X80: int64
X81: int64
X82: int64
X83: int64
X84: int64
X85: int64
X86: int64
X87: int64
X88: int64
X89: int64
X90: int64
X91: int64
X92: int64
X93: int64
X94: int64
X95: int64
X96: int64
X97: int64
X98: int64
X99: int64
X100: int64
X101: int64
X102: int64
X103: int64
X104: int64
X105: int64
X106: int64
X107: int64
X108: int64
X109: int64
X110: int64
X111: int64
X112: int64
X113: int64
X114: int64
X115: int64
X116: int64
X117: int64
X118: int64
X119: int64
X120: int64
X122: int64
X123: int64
X124: int64
X125: int64
X126: int64
X127: int64
X128: int64
X129: int64
X130: int64
X131: int64
X132: int64
X133: int64
X134: int64
X135: int64
X136: int64
X137: int64
X138: int64
X139: int64
X140: int64
X141: int64
X142: int64
X143: int64
X144: int64
X145: int64
X146: int64
X147: int64
X148: int64
X150: int64
X151: int64
X152: int64
X153: int64
X154: int64
X155: int64
X156: int64
X157: int64
X158: int64
X159: int64
X160: int64
X161: int64
X162: int64
X163: int64
X164: int64
X165: int64
X166: int64
X167: int64
X168: int64
X169: int64
X170: int64
X171: int64
X172: int64
X173: int64
X174: int64
X175: int64
X176: int64
X177: int64
X178: int64
X179: int64
X180: int64
X181: int64
X182: int64
X183: int64
X184: int64
X185: int64
X186: int64
X187: int64
X189: int64
X190: int64
X191: int64
X192: int64
X194: int64
X195: int64
X196: int64
X197: int64
X198: int64
X199: int64
X200: int64
X201: int64
X202: int64
X203: int64
X204: int64
X205: int64
X206: int64
X207: int64
X208: int64
X209: int64
X210: int64
X211: int64
X212: int64
X213: int64
X214: int64
X215: int64
X216: int64
X217: int64
X218: int64
X219: int64
X220: int64
X221: int64
X222: int64
X223: int64
X224: int64
X225: int64
X226: int64
X227: int64
X228: int64
X229: int64
X230: int64
X231: int64
X232: int64
X233: int64
X234: int64
X235: int64
X236: int64
X237: int64
X238: int64
X239: int64
X240: int64
X241: int64
X242: int64
X243: int64
X244: int64
X245: int64
X246: int64
X247: int64
X248: int64
X249: int64
X250: int64
X251: int64
X252: int64
X253: int64
X254: int64
X255: int64
X256: int64
X257: int64
X258: int64
X259: int64
X260: int64
X261: int64
X262: int64
X263: int64
X264: int64
X265: int64
X266: int64
X267: int64
X268: int64
X269: int64
X270: int64
X271: int64
X272: int64
X273: int64
X274: int64
X275: int64
X276: int64
X277: int64
X278: int64
X279: int64
X280: int64
X281: int64
X282: int64
X283: int64
X284: int64
X285: int64
X286: int64
X287: int64
X288: int64
X289: int64
X290: int64
X291: int64
X292: int64
X293: int64
X294: int64
X295: int64
X296: int64
X297: int64
X298: int64
X299: int64
X300: int64
X301: int64
X302: int64
X304: int64
X305: int64
X306: int64
X307: int64
X308: int64
X309: int64
X310: int64
X311: int64
X312: int64
X313: int64
X314: int64
X315: int64
X316: int64
X317: int64
X318: int64
X319: int64
X320: int64
X321: int64
X322: int64
X323: int64
X324: int64
X325: int64
X326: int64
X327: int64
X328: int64
X329: int64
X330: int64
X331: int64
X332: int64
X333: int64
X334: int64
X335: int64
X336: int64
X337: int64
X338: int64
X339: int64
X340: int64
X341: int64
X342: int64
X343: int64
X344: int64
X345: int64
X346: int64
X347: int64
X348: int64
X349: int64
X350: int64
X351: int64
X352: int64
X353: int64
X354: int64
X355: int64
X356: int64
X357: int64
X358: int64
X359: int64
X360: int64
X361: int64
X362: int64
X363: int64
X364: int64
X365: int64
X366: int64
X367: int64
X368: int64
X369: int64
X370: int64
X371: int64
X372: int64
X373: int64
X374: int64
X375: int64
X376: int64
X377: int64
X378: int64
X379: int64
X380: int64
X382: int64
X383: int64
X384: int64
X385: int64

# Count the data in each of the columns

In [75]:
print("\nTrain Data - Value Counts:")
for col in train.columns:
    print(f"{col}:\n{train[col].value_counts()}\n")

Train Data - Value Counts:
ID:
0       1
5600    1
5604    1
5606    1
5611    1
       ..
2788    1
2790    1
2791    1
2793    1
8417    1
Name: ID, Length: 4209, dtype: int64

y:
91.88     7
89.38     7
89.06     7
90.76     7
89.19     6
         ..
110.90    1
132.60    1
94.08     1
75.89     1
87.48     1
Name: y, Length: 2545, dtype: int64

X0:
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

X1:
aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
w      52
z      46
u      37
e      33
m      32
t      31
h      29
y      23
f      23
j      22
n      19
k      17
p       9
g       6
d       3
q       3
ab      3
Name: X1, dtype: int64

X2:
as    1659
ae     496
ai     415
m      367
ak     265
r      153
n      137
s       94
f       87
e       81
aq      63
ay      54
a       47
t       29
k       25
i       25
b       21
ao      20
ag      19
z       19
d       18
ac      13
g       12
ap      11
y       11
x       10
aw       8
at       6
h        6
al       5
an       5
q        5
av       4
ah       4
p        4
au       3
am       1
j        1
af       1
l        1
aa       1
c        1
o        1
ar       1
Name: X2, dtype: int64

X3:
c    1942
f    1076
a     440
d     290
g     241
e     163
b      57
Name: X3, dtype: int64

X4:
d    4205
a       2
b       1
c       1
Name: X4, dtype: int64

X5:
w     231
v     231
q     220
r     215
s     214
d     214
n     212
p     208
m     208
i     207
ae    205
ag    204
ac    200
ab    197
l     195
af    188
ad    185
k     177
c     131
j     125
aa    112
ah     97
o      20
f       7
x       2
y       1
g       1
h       1
u       1
Name: X5, dtype: int64

X6:
g    1042
j    1039
d     625
i     488
l     478
a     206
h     190
k      43
c      38
b      28
f      20
e      12
Name: X6, dtype: int64

X8:
j    277
s    255
f    243
n    242
i    237
e    225
r    219
a    210
w    196
v    194
b    190
k    176
o    163
m    155
g    130
u    119
t    119
q    117
h    117
y    116
x    105
d    103
l    101
p    100
c    100
Name: X8, dtype: int64

X10:
0    4153
1      56
Name: X10, dtype: int64

X11:
0    4209
Name: X11, dtype: int64

X12:
0    3893
1     316
Name: X12, dtype: int64

X13:
0    3965
1     244
Name: X13, dtype: int64

X14:
0    2407
1    1802
Name: X14, dtype: int64

X15:
0    4207
1       2
Name: X15, dtype: int64

X16:
0    4198
1      11
Name: X16, dtype: int64

X17:
0    4177
1      32
Name: X17, dtype: int64

X18:
0    4176
1      33
Name: X18, dtype: int64

X19:
0    3790
1     419
Name: X19, dtype: int64

X20:
0    3608
1     601
Name: X20, dtype: int64

X21:
0    4198
1      11
Name: X21, dtype: int64

X22:
0    3843
1     366
Name: X22, dtype: int64

X23:
0    4122
1      87
Name: X23, dtype: int64

X24:
0    4201
1       8
Name: X24, dtype: int64

X26:
0    4188
1      21
Name: X26, dtype: int64

X27:
1    2873
0    1336
Name: X27, dtype: int64

X28:
0    4072
1     137
Name: X28, dtype: int64

X29:
0    4028
1     181
Name: X29, dtype: int64

X30:
0    4190
1      19
Name: X30, dtype: int64

X31:
0    3231
1     978
Name: X31, dtype: int64

X32:
0    4162
1      47
Name: X32, dtype: int64

X33:
0    4208
1       1
Name: X33, dtype: int64

X34:
0    4186
1      23
Name: X34, dtype: int64

X35:
0    3231
1     978
Name: X35, dtype: int64

X36:
0    4190
1      19
Name: X36, dtype: int64

X37:
0    3231
1     978
Name: X37, dtype: int64

X38:
0    4069
1     140
Name: X38, dtype: int64

X39:
0    4208
1       1
Name: X39, dtype: int64

X40:
0    4206
1       3
Name: X40, dtype: int64

X41:
0    4161
1      48
Name: X41, dtype: int64

X42:
0    4208
1       1
Name: X42, dtype: int64

X43:
0    3905
1     304
Name: X43, dtype: int64

X44:
0    4161
1      48
Name: X44, dtype: int64

X45:
0    3143
1    1066
Name: X45, dtype: int64

X46:
1    2514
0    1695
Name: X46, dtype: int64

X47:
0    4155
1      54
Name: X47, dtype: int64

X48:
0    4115
1      94
Name: X48, dtype: int64

X49:
0    3695
1     514
Name: X49, dtype: int64

X50:
0    3308
1     901
Name: X50, dtype: int64

X51:
1    3038
0    1171
Name: X51, dtype: int64

X52:
0    4031
1     178
Name: X52, dtype: int64

X53:
0    4180
1      29
Name: X53, dtype: int64

X54:
0    4026
1     183
Name: X54, dtype: int64

X55:
0    4187
1      22
Name: X55, dtype: int64

X56:
0    4120
1      89
Name: X56, dtype: int64

X57:
0    4153
1      56
Name: X57, dtype: int64

X58:
1    2420
0    1789
Name: X58, dtype: int64

X59:
0    4206
1       3
Name: X59, dtype: int64

X60:
0    4203
1       6
Name: X60, dtype: int64

X61:
1    4015
0     194
Name: X61, dtype: int64

X62:
0    4184
1      25
Name: X62, dtype: int64

X63:
0    4161
1      48
Name: X63, dtype: int64

X64:
0    2630
1    1579
Name: X64, dtype: int64

X65:
0    4200
1       9
Name: X65, dtype: int64

X66:
0    4095
1     114
Name: X66, dtype: int64

X67:
0    4201
1       8
Name: X67, dtype: int64

X68:
0    3900
1     309
Name: X68, dtype: int64

X69:
0    4083
1     126
Name: X69, dtype: int64

X70:
1    3872
0     337
Name: X70, dtype: int64

X71:
0    3773
1     436
Name: X71, dtype: int64

X73:
0    4125
1      84
Name: X73, dtype: int64

X74:
1    4206
0       3
Name: X74, dtype: int64

X75:
0    4057
1     152
Name: X75, dtype: int64

X76:
0    4026
1     183
Name: X76, dtype: int64

X77:
0    4156
1      53
Name: X77, dtype: int64

X78:
0    4185
1      24
Name: X78, dtype: int64

X79:
0    4103
1     106
Name: X79, dtype: int64

X80:
1    3986
0     223
Name: X80, dtype: int64

X81:
0    3245
1     964
Name: X81, dtype: int64

X82:
0    4137
1      72
Name: X82, dtype: int64

X83:
0    4204
1       5
Name: X83, dtype: int64

X84:
0    3773
1     436
Name: X84, dtype: int64

X85:
0    2491
1    1718
Name: X85, dtype: int64

X86:
0    4203
1       6
Name: X86, dtype: int64

X87:
0    4205
1       4
Name: X87, dtype: int64

X88:
0    4179
1      30
Name: X88, dtype: int64

X89:
0    4206
1       3
Name: X89, dtype: int64

X90:
0    4178
1      31
Name: X90, dtype: int64

X91:
0    4202
1       7
Name: X91, dtype: int64

X92:
0    4205
1       4
Name: X92, dtype: int64

X93:
0    4209
Name: X93, dtype: int64

X94:
0    4178
1      31
Name: X94, dtype: int64

X95:
0    4208
1       1
Name: X95, dtype: int64

X96:
1    3191
0    1018
Name: X96, dtype: int64

X97:
0    4191
1      18
Name: X97, dtype: int64

X98:
1    3967
0     242
Name: X98, dtype: int64

X99:
0    4173
1      36
Name: X99, dtype: int64

X100:
1    2905
0    1304
Name: X100, dtype: int64

X101:
1    3938
0     271
Name: X101, dtype: int64

X102:
0    4180
1      29
Name: X102, dtype: int64

X103:
1    3302
0     907
Name: X103, dtype: int64

X104:
0    4201
1       8
Name: X104, dtype: int64

X105:
0    4199
1      10
Name: X105, dtype: int64

X106:
0    4154
1      55
Name: X106, dtype: int64

X107:
0    4209
Name: X107, dtype: int64

X108:
0    4147
1      62
Name: X108, dtype: int64

X109:
0    4039
1     170
Name: X109, dtype: int64

X110:
0    4205
1       4
Name: X110, dtype: int64

X111:
1    4103
0     106
Name: X111, dtype: int64

X112:
0    4197
1      12
Name: X112, dtype: int64

X113:
0    4115
1      94
Name: X113, dtype: int64

X114:
0    3594
1     615
Name: X114, dtype: int64

X115:
0    3007
1    1202
Name: X115, dtype: int64

X116:
0    3381
1     828
Name: X116, dtype: int64

X117:
0    4002
1     207
Name: X117, dtype: int64

X118:
1    2619
0    1590
Name: X118, dtype: int64

X119:
1    2619
0    1590
Name: X119, dtype: int64

X120:
1    4031
0     178
Name: X120, dtype: int64

X122:
0    4179
1      30
Name: X122, dtype: int64

X123:
0    4198
1      11
Name: X123, dtype: int64

X124:
0    4207
1       2
Name: X124, dtype: int64

X125:
0    4196
1      13
Name: X125, dtype: int64

X126:
0    4045
1     164
Name: X126, dtype: int64

X127:
0    2125
1    2084
Name: X127, dtype: int64

X128:
1    4034
0     175
Name: X128, dtype: int64

X129:
0    3693
1     516
Name: X129, dtype: int64

X130:
0    4034
1     175
Name: X130, dtype: int64

X131:
0    4097
1     112
Name: X131, dtype: int64

X132:
1    2898
0    1311
Name: X132, dtype: int64

X133:
0    3686
1     523
Name: X133, dtype: int64

X134:
0    4115
1      94
Name: X134, dtype: int64

X135:
0    4095
1     114
Name: X135, dtype: int64

X136:
1    4026
0     183
Name: X136, dtype: int64

X137:
1    2449
0    1760
Name: X137, dtype: int64

X138:
0    4037
1     172
Name: X138, dtype: int64

X139:
0    3828
1     381
Name: X139, dtype: int64

X140:
0    4039
1     170
Name: X140, dtype: int64

X141:
0    4149
1      60
Name: X141, dtype: int64

X142:
1    3242
0     967
Name: X142, dtype: int64

X143:
0    4048
1     161
Name: X143, dtype: int64

X144:
1    3401
0     808
Name: X144, dtype: int64

X145:
0    4203
1       6
Name: X145, dtype: int64

X146:
0    4037
1     172
Name: X146, dtype: int64

X147:
0    4115
1      94
Name: X147, dtype: int64

X148:
0    4020
1     189
Name: X148, dtype: int64

X150:
1    3335
0     874
Name: X150, dtype: int64

X151:
0    3849
1     360
Name: X151, dtype: int64

X152:
0    4073
1     136
Name: X152, dtype: int64

X153:
0    4206
1       3
Name: X153, dtype: int64

X154:
0    3330
1     879
Name: X154, dtype: int64

X155:
0    3887
1     322
Name: X155, dtype: int64

X156:
1    3019
0    1190
Name: X156, dtype: int64

X157:
0    3019
1    1190
Name: X157, dtype: int64

X158:
0    3242
1     967
Name: X158, dtype: int64

X159:
0    4152
1      57
Name: X159, dtype: int64

X160:
0    4204
1       5
Name: X160, dtype: int64

X161:
0    3377
1     832
Name: X161, dtype: int64

X162:
0    4037
1     172
Name: X162, dtype: int64

X163:
0    2932
1    1277
Name: X163, dtype: int64

X164:
0    3946
1     263
Name: X164, dtype: int64

X165:
0    4190
1      19
Name: X165, dtype: int64

X166:
0    4069
1     140
Name: X166, dtype: int64

X167:
0    4205
1       4
Name: X167, dtype: int64

X168:
0    3069
1    1140
Name: X168, dtype: int64

X169:
0    4181
1      28
Name: X169, dtype: int64

X170:
0    4107
1     102
Name: X170, dtype: int64

X171:
1    2767
0    1442
Name: X171, dtype: int64

X172:
0    4184
1      25
Name: X172, dtype: int64

X173:
0    4168
1      41
Name: X173, dtype: int64

X174:
0    4136
1      73
Name: X174, dtype: int64

X175:
0    4115
1      94
Name: X175, dtype: int64

X176:
0    4137
1      72
Name: X176, dtype: int64

X177:
0    3998
1     211
Name: X177, dtype: int64

X178:
1    2346
0    1863
Name: X178, dtype: int64

X179:
0    4007
1     202
Name: X179, dtype: int64

X180:
0    3544
1     665
Name: X180, dtype: int64

X181:
0    3814
1     395
Name: X181, dtype: int64

X182:
0    3762
1     447
Name: X182, dtype: int64

X183:
0    4192
1      17
Name: X183, dtype: int64

X184:
0    4203
1       6
Name: X184, dtype: int64

X185:
0    4130
1      79
Name: X185, dtype: int64

X186:
1    2256
0    1953
Name: X186, dtype: int64

X187:
0    2439
1    1770
Name: X187, dtype: int64

X189:
1    3853
0     356
Name: X189, dtype: int64

X190:
0    4208
1       1
Name: X190, dtype: int64

X191:
0    2227
1    1982
Name: X191, dtype: int64

X192:
0    4199
1      10
Name: X192, dtype: int64

X194:
0    2256
1    1953
Name: X194, dtype: int64

X195:
0    4160
1      49
Name: X195, dtype: int64

X196:
0    4166
1      43
Name: X196, dtype: int64

X197:
0    4073
1     136
Name: X197, dtype: int64

X198:
0    4112
1      97
Name: X198, dtype: int64

X199:
0    4197
1      12
Name: X199, dtype: int64

X200:
0    4181
1      28
Name: X200, dtype: int64

X201:
0    3461
1     748
Name: X201, dtype: int64

X202:
0    3193
1    1016
Name: X202, dtype: int64

X203:
0    4138
1      71
Name: X203, dtype: int64

X204:
0    4208
1       1
Name: X204, dtype: int64

X205:
1    4208
0       1
Name: X205, dtype: int64

X206:
0    4128
1      81
Name: X206, dtype: int64

X207:
0    4208
1       1
Name: X207, dtype: int64

X208:
0    3944
1     265
Name: X208, dtype: int64

X209:
1    3782
0     427
Name: X209, dtype: int64

X210:
0    4208
1       1
Name: X210, dtype: int64

X211:
0    4146
1      63
Name: X211, dtype: int64

X212:
0    4186
1      23
Name: X212, dtype: int64

X213:
0    4201
1       8
Name: X213, dtype: int64

X214:
0    4180
1      29
Name: X214, dtype: int64

X215:
0    3794
1     415
Name: X215, dtype: int64

X216:
0    4184
1      25
Name: X216, dtype: int64

X217:
0    4178
1      31
Name: X217, dtype: int64

X218:
0    2894
1    1315
Name: X218, dtype: int64

X219:
0    3925
1     284
Name: X219, dtype: int64

X220:
1    2362
0    1847
Name: X220, dtype: int64

X221:
0    4175
1      34
Name: X221, dtype: int64

X222:
0    4115
1      94
Name: X222, dtype: int64

X223:
1    2337
0    1872
Name: X223, dtype: int64

X224:
0    2873
1    1336
Name: X224, dtype: int64

X225:
0    3801
1     408
Name: X225, dtype: int64

X226:
0    4073
1     136
Name: X226, dtype: int64

X227:
0    4196
1      13
Name: X227, dtype: int64

X228:
0    4045
1     164
Name: X228, dtype: int64

X229:
1    4041
0     168
Name: X229, dtype: int64

X230:
0    4187
1      22
Name: X230, dtype: int64

X231:
0    4141
1      68
Name: X231, dtype: int64

X232:
0    4028
1     181
Name: X232, dtype: int64

X233:
0    4209
Name: X233, dtype: int64

X234:
0    3360
1     849
Name: X234, dtype: int64

X235:
0    4209
Name: X235, dtype: int64

X236:
0    4207
1       2
Name: X236, dtype: int64

X237:
0    4181
1      28
Name: X237, dtype: int64

X238:
1    3856
0     353
Name: X238, dtype: int64

X239:
0    4180
1      29
Name: X239, dtype: int64

X240:
0    4197
1      12
Name: X240, dtype: int64

X241:
0    3800
1     409
Name: X241, dtype: int64

X242:
0    4178
1      31
Name: X242, dtype: int64

X243:
0    4179
1      30
Name: X243, dtype: int64

X244:
0    3773
1     436
Name: X244, dtype: int64

X245:
0    4206
1       3
Name: X245, dtype: int64

X246:
0    2486
1    1723
Name: X246, dtype: int64

X247:
0    3193
1    1016
Name: X247, dtype: int64

X248:
0    4203
1       6
Name: X248, dtype: int64

X249:
0    4177
1      32
Name: X249, dtype: int64

X250:
1    2327
0    1882
Name: X250, dtype: int64

X251:
0    2550
1    1659
Name: X251, dtype: int64

X252:
0    4206
1       3
Name: X252, dtype: int64

X253:
0    4203
1       6
Name: X253, dtype: int64

X254:
0    4187
1      22
Name: X254, dtype: int64

X255:
0    4127
1      82
Name: X255, dtype: int64

X256:
0    3901
1     308
Name: X256, dtype: int64

X257:
0    4208
1       1
Name: X257, dtype: int64

X258:
0    4199
1      10
Name: X258, dtype: int64

X259:
0    4208
1       1
Name: X259, dtype: int64

X260:
0    4208
1       1
Name: X260, dtype: int64

X261:
0    2443
1    1766
Name: X261, dtype: int64

X262:
0    4203
1       6
Name: X262, dtype: int64

X263:
1    4028
0     181
Name: X263, dtype: int64

X264:
0    4043
1     166
Name: X264, dtype: int64

X265:
1    3811
0     398
Name: X265, dtype: int64

X266:
0    4203
1       6
Name: X266, dtype: int64

X267:
0    4171
1      38
Name: X267, dtype: int64

X268:
0    4209
Name: X268, dtype: int64

X269:
0    4207
1       2
Name: X269, dtype: int64

X270:
0    4208
1       1
Name: X270, dtype: int64

X271:
0    4200
1       9
Name: X271, dtype: int64

X272:
0    4051
1     158
Name: X272, dtype: int64

X273:
1    3031
0    1178
Name: X273, dtype: int64

X274:
0    4167
1      42
Name: X274, dtype: int64

X275:
1    3059
0    1150
Name: X275, dtype: int64

X276:
0    4047
1     162
Name: X276, dtype: int64

X277:
0    4203
1       6
Name: X277, dtype: int64

X278:
0    4207
1       2
Name: X278, dtype: int64

X279:
0    4028
1     181
Name: X279, dtype: int64

X280:
0    4208
1       1
Name: X280, dtype: int64

X281:
0    4198
1      11
Name: X281, dtype: int64

X282:
0    4192
1      17
Name: X282, dtype: int64

X283:
0    3617
1     592
Name: X283, dtype: int64

X284:
0    4036
1     173
Name: X284, dtype: int64

X285:
0    3343
1     866
Name: X285, dtype: int64

X286:
0    3979
1     230
Name: X286, dtype: int64

X287:
0    4142
1      67
Name: X287, dtype: int64

X288:
0    4208
1       1
Name: X288, dtype: int64

X289:
0    4209
Name: X289, dtype: int64

X290:
0    4209
Name: X290, dtype: int64

X291:
0    4165
1      44
Name: X291, dtype: int64

X292:
0    4171
1      38
Name: X292, dtype: int64

X293:
0    4209
Name: X293, dtype: int64

X294:
0    3683
1     526
Name: X294, dtype: int64

X295:
0    4208
1       1
Name: X295, dtype: int64

X296:
0    4208
1       1
Name: X296, dtype: int64

X297:
0    4209
Name: X297, dtype: int64

X298:
0    4190
1      19
Name: X298, dtype: int64

X299:
0    4190
1      19
Name: X299, dtype: int64

X300:
0    3338
1     871
Name: X300, dtype: int64

X301:
0    4012
1     197
Name: X301, dtype: int64

X302:
0    4161
1      48
Name: X302, dtype: int64

X304:
1    3890
0     319
Name: X304, dtype: int64

X305:
0    4153
1      56
Name: X305, dtype: int64

X306:
0    4025
1     184
Name: X306, dtype: int64

X307:
0    4200
1       9
Name: X307, dtype: int64

X308:
0    4169
1      40
Name: X308, dtype: int64

X309:
0    4179
1      30
Name: X309, dtype: int64

X310:
0    4198
1      11
Name: X310, dtype: int64

X311:
1    2519
0    1690
Name: X311, dtype: int64

X312:
0    4191
1      18
Name: X312, dtype: int64

X313:
0    2942
1    1267
Name: X313, dtype: int64

X314:
0    2392
1    1817
Name: X314, dtype: int64

X315:
0    4088
1     121
Name: X315, dtype: int64

X316:
0    3386
1     823
Name: X316, dtype: int64

X317:
0    4177
1      32
Name: X317, dtype: int64

X318:
0    4206
1       3
Name: X318, dtype: int64

X319:
0    4207
1       2
Name: X319, dtype: int64

X320:
0    4179
1      30
Name: X320, dtype: int64

X321:
0    3204
1    1005
Name: X321, dtype: int64

X322:
0    4117
1      92
Name: X322, dtype: int64

X323:
0    4170
1      39
Name: X323, dtype: int64

X324:
1    2420
0    1789
Name: X324, dtype: int64

X325:
0    4185
1      24
Name: X325, dtype: int64

X326:
0    4073
1     136
Name: X326, dtype: int64

X327:
0    3669
1     540
Name: X327, dtype: int64

X328:
0    4040
1     169
Name: X328, dtype: int64

X329:
0    2377
1    1832
Name: X329, dtype: int64

X330:
0    4209
Name: X330, dtype: int64

X331:
0    3973
1     236
Name: X331, dtype: int64

X332:
0    4206
1       3
Name: X332, dtype: int64

X333:
0    4108
1     101
Name: X333, dtype: int64

X334:
0    2262
1    1947
Name: X334, dtype: int64

X335:
0    4194
1      15
Name: X335, dtype: int64

X336:
0    3673
1     536
Name: X336, dtype: int64

X337:
1    2174
0    2035
Name: X337, dtype: int64

X338:
0    4180
1      29
Name: X338, dtype: int64

X339:
0    4208
1       1
Name: X339, dtype: int64

X340:
0    4115
1      94
Name: X340, dtype: int64

X341:
0    4175
1      34
Name: X341, dtype: int64

X342:
0    4115
1      94
Name: X342, dtype: int64

X343:
0    3879
1     330
Name: X343, dtype: int64

X344:
0    4173
1      36
Name: X344, dtype: int64

X345:
0    4115
1      94
Name: X345, dtype: int64

X346:
0    4009
1     200
Name: X346, dtype: int64

X347:
0    4209
Name: X347, dtype: int64

X348:
1    3987
0     222
Name: X348, dtype: int64

X349:
0    4020
1     189
Name: X349, dtype: int64

X350:
0    2783
1    1426
Name: X350, dtype: int64

X351:
0    2958
1    1251
Name: X351, dtype: int64

X352:
0    3981
1     228
Name: X352, dtype: int64

X353:
0    4200
1       9
Name: X353, dtype: int64

X354:
0    3355
1     854
Name: X354, dtype: int64

X355:
0    2608
1    1601
Name: X355, dtype: int64

X356:
0    3452
1     757
Name: X356, dtype: int64

X357:
0    4204
1       5
Name: X357, dtype: int64

X358:
0    2412

# Read the test.csv data

In [76]:
test = pd.read_csv("test.csv")

# Check for null and unique values for test and train set

In [92]:
print("\nTrain Data - Null Values:\n", train.isnull().sum())
print("\nTrain Data - Unique Values:\n", train.nunique())
print("\nTest Data - Null Values:\n", test.isnull().sum())
print("\nTest Data - Unique Values:\n", test.nunique())

Train Data - Null Values:
 y       0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 377, dtype: int64

Train Data - Unique Values:
 y       2545
X0        47
X1        27
X2        44
X3         7
        ...
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 377, dtype: int64

Test Data - Null Values:
 X0      0
X1      0
X2      0
X3      0
X4      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 376, dtype: int64

Test Data - Unique Values:
 X0      49
X1      27
X2      45
X3       7
X4       4
        ..
X380     2
X382     2
X383     2
X384     2
X385     2
Length: 376, dtype: int64

In [77]:
train = train.drop('ID',axis =1)
test = test.drop('ID',axis =1)

In [78]:
X = train.drop('y',axis=1).copy()
y = train.y

In [79]:
X.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,k,v,at,a,d,u,j,o,0,0,...,0,0,1,0,0,0,0,0,0,0
1,k,t,av,e,d,y,l,o,0,0,...,1,0,0,0,0,0,0,0,0,0
2,az,w,n,c,d,x,j,x,0,0,...,0,0,0,0,0,0,1,0,0,0
3,az,t,n,f,d,x,l,e,0,0,...,0,0,0,0,0,0,0,0,0,0
4,az,v,n,f,d,h,d,n,0,0,...,0,0,0,0,0,0,0,0,0,0

In [80]:
y.head()

0    130.81
1     88.53
2     76.26
3     80.62
4     78.02
Name: y, dtype: float64

In [81]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                                random_state=0)

In [82]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Function for comparing different approaches
def score_dataset(X_train, X_valid, y_train, y_valid):
    model = RandomForestRegressor(n_estimators=100, random_state=0)
    model.fit(X_train, y_train)
    preds = model.predict(X_valid)
    return mean_absolute_error(y_valid, preds)

In [85]:
X_desc = X.describe(include='O')
X_desc

          X0    X1    X2    X3    X4    X5    X6    X8
count   4209  4209  4209  4209  4209  4209  4209  4209
unique    47    27    44     7     4    29    12    25
top        z    aa    as     c     d     w     g     j
freq     360   833  1659  1942  4205   231  1042   277

# Label Encoder

In [86]:
from sklearn.preprocessing import LabelEncoder

# Make copy to avoid changing original data 
le_X_train = X_train.copy()
le_X_valid = X_valid.copy()

# Apply ordinal encoder to each column with categorical data
le= LabelEncoder()
#X_train[X_desc.columns] = le.fit_transform(X_train[X_desc.columns])
#X_valid[X_desc.columns] = le.fit_transform(X_valid[X_desc.columns])

for i in X_desc.columns:
    le_X_train[i]=le.fit_transform(le_X_train[i])
for i in X_desc.columns:
    le_X_valid[i]=le.fit_transform(le_X_valid[i])

print("MAE from Approach 1 (Lable Encoding):") 
print(score_dataset(le_X_train, le_X_valid, y_train, y_valid))

MAE from Approach 1 (Lable Encoding):
6.850257963457775

# Make sure the data is now changed into numericals

In [87]:
le_X_train.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
3540,6,13,15,5,3,22,8,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3748,7,23,37,0,3,25,6,4,0,0,...,0,0,1,0,0,0,0,0,0,0
1287,28,0,8,5,3,2,9,20,0,0,...,0,0,0,0,0,0,0,0,0,0
2856,18,19,37,5,3,20,6,6,0,0,...,0,0,0,0,0,0,0,0,0,0
1380,11,13,38,2,3,2,3,13,0,0,...,0,0,0,0,0,0,0,0,0,0

In [88]:
from sklearn.preprocessing import OrdinalEncoder

# Make copy to avoid changing original data 
label_X_train = X_train.copy()
label_X_valid = X_valid.copy()

# Apply ordinal encoder to each column with categorical data
ordinal_encoder = OrdinalEncoder()
label_X_train[X_desc.columns] = ordinal_encoder.fit_transform(label_X_train[X_desc.columns])
label_X_valid[X_desc.columns] = ordinal_encoder.fit_transform(label_X_valid[X_desc.columns])

print("MAE from Approach 2 (Ordinal Encoding):") 
print(score_dataset(label_X_train, label_X_valid, y_train, y_valid))

MAE from Approach 2 (Ordinal Encoding):
6.850257963457775

# Encoding test data

In [89]:
lable_test = test.copy()

for i in X_desc.columns:
    lable_test[i]=le.fit_transform(lable_test[i])

In [90]:
label_X_train.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
3540,6.0,13.0,15.0,5.0,3.0,22.0,8.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3748,7.0,23.0,37.0,0.0,3.0,25.0,6.0,4.0,0,0,...,0,0,1,0,0,0,0,0,0,0
1287,28.0,0.0,8.0,5.0,3.0,2.0,9.0,20.0,0,0,...,0,0,0,0,0,0,0,0,0,0
2856,18.0,19.0,37.0,5.0,3.0,20.0,6.0,6.0,0,0,...,0,0,0,0,0,0,0,0,0,0
1380,11.0,13.0,38.0,2.0,3.0,2.0,3.0,13.0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Scaling Data

In [95]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(le_X_train)
X_valid_scaled = scaler.fit_transform(le_X_valid)
test_scaled = scaler.fit_transform(lable_test)

In [96]:
columns = []
for col in le_X_train.columns:
    columns.append(col)
columns

['X0',
 'X1',
 'X2',
 'X3',
 'X4',
 'X5',
 'X6',
 'X8',
 'X10',
 'X11',
 'X12',
 'X13',
 'X14',
 'X15',
 'X16',
 'X17',
 'X18',
 'X19',
 'X20',
 'X21',
 'X22',
 'X23',
 'X24',
 'X26',
 'X27',
 'X28',
 'X29',
 'X30',
 'X31',
 'X32',
 'X33',
 'X34',
 'X35',
 'X36',
 'X37',
 'X38',
 'X39',
 'X40',
 'X41',
 'X42',
 'X43',
 'X44',
 'X45',
 'X46',
 'X47',
 'X48',
 'X49',
 'X50',
 'X51',
 'X52',
 'X53',
 'X54',
 'X55',
 'X56',
 'X57',
 'X58',
 'X59',
 'X60',
 'X61',
 'X62',
 'X63',
 'X64',
 'X65',
 'X66',
 'X67',
 'X68',
 'X69',
 'X70',
 'X71',
 'X73',
 'X74',
 'X75',
 'X76',
 'X77',
 'X78',
 'X79',
 'X80',
 'X81',
 'X82',
 'X83',
 'X84',
 'X85',
 'X86',
 'X87',
 'X88',
 'X89',
 'X90',
 'X91',
 'X92',
 'X93',
 'X94',
 'X95',
 'X96',
 'X97',
 'X98',
 'X99',
 'X100',
 'X101',
 'X102',
 'X103',
 'X104',
 'X105',
 'X106',
 'X107',
 'X108',
 'X109',
 'X110',
 'X111',
 'X112',
 'X113',
 'X114',
 'X115',
 'X116',
 'X117',
 'X118',
 'X119',
 'X120',
 'X122',
 'X123',
 'X124',
 'X125',
 'X126',
 'X127',
 'X128',
 'X129',
 'X130',
 'X131',
 'X132',
 'X133',
 'X134',
 'X135',
 'X136',
 'X137',
 'X138',
 'X139',
 'X140',
 'X141',
 'X142',
 'X143',
 'X144',
 'X145',
 'X146',
 'X147',
 'X148',
 'X150',
 'X151',
 'X152',
 'X153',
 'X154',
 'X155',
 'X156',
 'X157',
 'X158',
 'X159',
 'X160',
 'X161',
 'X162',
 'X163',
 'X164',
 'X165',
 'X166',
 'X167',
 'X168',
 'X169',
 'X170',
 'X171',
 'X172',
 'X173',
 'X174',
 'X175',
 'X176',
 'X177',
 'X178',
 'X179',
 'X180',
 'X181',
 'X182',
 'X183',
 'X184',
 'X185',
 'X186',
 'X187',
 'X189',
 'X190',
 'X191',
 'X192',
 'X194',
 'X195',
 'X196',
 'X197',
 'X198',
 'X199',
 'X200',
 'X201',
 'X202',
 'X203',
 'X204',
 'X205',
 'X206',
 'X207',
 'X208',
 'X209',
 'X210',
 'X211',
 'X212',
 'X213',
 'X214',
 'X215',
 'X216',
 'X217',
 'X218',
 'X219',
 'X220',
 'X221',
 'X222',
 'X223',
 'X224',
 'X225',
 'X226',
 'X227',
 'X228',
 'X229',
 'X230',
 'X231',
 'X232',
 'X233',
 'X234',
 'X235',
 'X236',
 'X237',
 'X238',
 'X239',
 'X240',
 'X241',
 'X242',
 'X243',
 'X244',
 'X245',
 'X246',
 'X247',
 'X248',
 'X249',
 'X250',
 'X251',
 'X252',
 'X253',
 'X254',
 'X255',
 'X256',
 'X257',
 'X258',
 'X259',
 'X260',
 'X261',
 'X262',
 'X263',
 'X264',
 'X265',
 'X266',
 'X267',
 'X268',
 'X269',
 'X270',
 'X271',
 'X272',
 'X273',
 'X274',
 'X275',
 'X276',
 'X277',
 'X278',
 'X279',
 'X280',
 'X281',
 'X282',
 'X283',
 'X284',
 'X285',
 'X286',
 'X287',
 'X288',
 'X289',
 'X290',
 'X291',
 'X292',
 'X293',
 'X294',
 'X295',
 'X296',
 'X297',
 'X298',
 'X299',
 'X300',
 'X301',
 'X302',
 'X304',
 'X305',
 'X306',
 'X307',
 'X308',
 'X309',
 'X310',
 'X311',
 'X312',
 'X313',
 'X314',
 'X315',
 'X316',
 'X317',
 'X318',
 'X319',
 'X320',
 'X321',
 'X322',
 'X323',
 'X324',
 'X325',
 'X326',
 'X327',
 'X328',
 'X329',
 'X330',
 'X331',
 'X332',
 'X333',
 'X334',
 'X335',
 'X336',
 'X337',
 'X338',
 'X339',
 'X340',
 'X341',
 'X342',
 'X343',
 'X344',
 'X345',
 'X346',
 'X347',
 'X348',
 'X349',
 'X350',
 'X351',
 'X352',
 'X353',
 'X354',
 'X355',
 'X356',
 'X357',
 'X358',
 'X359',
 'X360',
 'X361',
 'X362',
 'X363',
 'X364',
 'X365',
 'X366',
 'X367',
 'X368',
 'X369',
 'X370',
 'X371',
 'X372',
 'X373',
 'X374',
 'X375',
 'X376',
 'X377',
 'X378',
 'X379',
 'X380',
 'X382',
 'X383',
 'X384',
 'X385']

In [97]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns = columns)
X_valid_scaled = pd.DataFrame(X_valid_scaled, columns = columns)
test_scaled = pd.DataFrame(test_scaled, columns = columns)

# Perform dimensionality reduction

In [93]:
from sklearn.decomposition import PCA
from xgboost import XGBRegressor
from sklearn.metrics import accuracy_score

In [98]:
pca =PCA(n_components=0.97, random_state=102)
Xtrain_trans=pca.fit_transform(X_train_scaled)
XValid_trans=pca.transform(X_valid_scaled)
test_trans=pca.transform(test_scaled)
print(X_train_scaled.shape)
print(Xtrain_trans.shape)
print(X_valid_scaled.shape)
print(XValid_trans.shape)
print(test_scaled.shape)
print(test_trans.shape)

(3367, 376)
(3367, 94)
(842, 376)
(842, 94)
(4209, 376)
(4209, 94)

# Training using xgboost

In [99]:
xgb=XGBRegressor(n_estimators=1000, learning_rate=0.05, n_jobs=4)

In [100]:
xgb1=XGBRegressor(n_estimators=500, learning_rate=0.05, n_jobs=4)

In [101]:
xgb1=XGBRegressor(n_estimators=500, learning_rate=0.05, n_jobs=4)

In [102]:
#xgb1.fit(Xtrain_trans,y_train)
xgb.fit(Xtrain_trans, y_train, 
             early_stopping_rounds=5, 
             eval_set=[(XValid_trans, y_valid)], 
             verbose=False)

C:\Users\neha0\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\sklearn.py:885: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1000, n_jobs=4,
             num_parallel_tree=None, random_state=None, ...)

In [103]:
ypred=xgb.predict(XValid_trans)

In [104]:
print(xgb.score(Xtrain_trans,y_train))
print(xgb.score(XValid_trans,y_valid))

0.7613000225296529
0.4189282586696066

# Predict test values using xgboost

In [105]:
output = pd.DataFrame(xgb.predict(test_trans))

In [107]:
output.head()

            0
0   79.199371
1   95.815475
2   80.688843
3   78.369598
4  111.716957